language: cpp
os: linux

dist: focal
sudo: false

addons:
    apt:
        sources:
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
        packages:
            - clang-11
            - clang-tools-11
            - llvm-11
            - llvm-11-dev

script:
- mkdir -p build && cd build && cmake -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11 -DENABLE_TESTS=ON .. && make
